version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @nestjs/cli dotenv-cli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - dotenv -e .env.production -- npm run build
artifacts:
  files:
    - "**/*"