version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/data/postgres
    restart: always
    ports:
      - "5432:5432"

  back:
    restart: unless-stopped
    build:
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      - db

volumes:
  db-data: