version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sidekick
    volumes:
      - db-data:/var/lib/data/postgres
      - ./db-dump:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  db-data: