name: Production

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
            
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          key: ${{ secrets.KEY_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd api-back
            git pull
            git checkout main
            npm ci
            npm run build
            npm run migrate:deploy:prod
            pm2 stop all && pm2 delete all
            pm2 start "npm run start:prod" --name api
